import jQuery from 'jquery';

const $ = jQuery;

const Web3 = require('web3');
const web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

// This file is generated by the Solidity compiler to easily interact with
// the contract using the web3 library.
const loginAbi = require('../solidity/build/contracts/Login.json').abi;
const LoginContract = web3.eth.contract(loginAbi);

const loginAttempt = loginContract.LoginAttempt();
loginAttempt.watch((error, event) => {
    console.log(error, event);
});
console.log(loginAttempt);

function buildUrl(path) {
    if(path[0] === '/') {
        path = path.substr(1);
    }
    // WARNING: SWITCH TO HTTPS WHEN USING IN PRODUCTION
    return `http://localhost:3000/${path}`;
}

let jwt = null;
let challenge = null;
let interval = null;

function ajax(url, data) {
    return $.ajax(url, {
        contentType: 'application/json',
        method: 'POST',
        data: JSON.stringify(data)
    });
}

function apiTest() {
    const text = "Testing API access";
    const element = $('#api-test');
    element.text(text);

    const data = {
        jwt: jwt
    };
    ajax(buildUrl('/apiTest'), data).done(response => {
        if(response.message) {
            element.text(`${text}: ${response.message}`);
        } else {
            element.text(`${text}: uhh, something went wrong`);
        }
    });
}

function pollForLogin() {
    const data = {
        jwt: jwt
    };
    ajax(buildUrl('/finishLogin'), data).done(response => {
        if(response.jwt && response.address) {
            jwt = response.jwt;

            clearInterval(interval);
            interval = null;
            challenge = null;

            $('#login-in-progress').hide();
            $('#logged-in').show();

            $('#logged-in-address').text(`Logged in as ${response.address}`);

            apiTest();
        }
    });
}

$('#login-form').submit(event => {
    event.preventDefault();

    const data = {
        address: $(event.target).children(':text').val()
    };

    ajax(buildUrl('/login'), data).done(response => {
        jwt = response.jwt;
        challenge = response.challenge;

        $(event.target).hide();
        $('#login-in-progress').show();
        $('#login-in-progress p').text(challenge);

        interval = setInterval(pollForLogin, 1000);
    });
});

